name: dotnet

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build
    - name: Test
      run: dotnet test
  
  deploy:
    needs: build
    runs-on: windows-latest
    steps:
    - name: Approve
      uses: trstringer/manual-approval@v1.9.0
      with:
        approvers: rosolko
    - name: Pack
      run: dotnet pack --output nupkgs
    - name: Push
      run: dotnet nuget push nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
